# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DHeroMap' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DHeroMap

  #  platform :ios, '8.0'
  pod 'AFNetworking', '~> 3.0'
  pod 'JSONModel'

  target 'DHeroMapTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DHeroMapUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
